/**:
  ros__parameters:
    # Orca
    # segmentation_image_color_sub_topic: "/cam_segmentation/image_color"
    # segmentation_image_id_sub_topic:    "/cam_segmentation/image_raw"
    # camera_rig
    segmentation_image_color_sub_topic: "/front_camera_seg/image_color"
    segmentation_image_id_sub_topic:    "/front_camera_seg/image_raw"