<?xml version="1.0"?>
<package format="3">
  <name>vortex_yolo_classifiy</name>
  <version>0.0.1</version>
  <description>PyTorch classifier ROS2 node</description>

  <maintainer email="gard@example.com">gard</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>