<?xml version="1.0"?>
<package format="3">
  <name>sonar_segmentation</name>
  <version>0.0.0</version>
  <description>Projects segmentation labels onto sonar images using depth data.</description>

  <maintainer email="you@email.com">Your Name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>opencv</depend>
  <depend>stonefish_ros2</depend>
  <depend>vortex_utils</depend>
  <depend>vortex_msgs</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
