/**:
  ros__parameters:
    segmentation_image_sub_topic: "/nautilus/segmentation_cam_down/image_color"
    color_image_sub_topic: "/nautilus/down_camera/image_color"
    output_dir: /home/kluge7/stonefish_labeling_output_new
    sync_tolerance_ms: 100 # Timestamps of the two topics from stonefish are not perfectly synced.
                          # This sets the max allowed time offset between the two topics.
